version: "2.1"
x-image: &default-image
  build: glitchtip
x-environment:
  &default-environment
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  SECRET_KEY: change_me
  PORT: 80
  AWS_ACCESS_KEY_ID: glitchtip
  AWS_SECRET_ACCESS_KEY: glitchtip
  AWS_STORAGE_BUCKET_NAME: glitchtip
  AWS_S3_ENDPOINT_URL: minio
  GLITCHTIP_MAX_EVENT_LIFE_DAYS: 90
  REDIS_HOST: redis
  REDIS_DATABASE: 0
  EMAIL_URL: "smtp://smtp:25"
x-depends_on:
  &default-depends_on
  - postgres
  - redis

volumes:
  minio: {}
  postgres: {}
  redis: {}

services:
  minio:
    command: "server /data"
    image: minio/minio:latest
    environment:
      BUCKETS: glitchtip
      MINIO_ROOT_USER: glitchtip
      MINIO_ROOT_PASSWORD: glitchtip
    volumes:
      - minio:/data
  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data
  smtp:
    image: namshi/smtp:latest
    restart: unless-stopped
  glitchtip:
    <<: *default-image
    depends_on: *default-depends_on
    ports:
      - "80:80"
    environment: *default-environment
    restart: unless-stopped
  glitchtip-worker:
    <<: *default-image
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    environment: *default-environment
    restart: unless-stopped
  glitchtip-migrate:
    <<: *default-image
    depends_on: *default-depends_on
    command: "./manage.py migrate"
    environment: *default-environment
    restart: no
